repos:
- repo: https://github.com/psf/black
  rev: 24.2.0
  hooks:
  - id: black
    language_version: python
    args: [--line-length=88, --quiet]

- repo: local
  hooks:
  - id: install-jobspy
    name: Install JobSpy
    entry: pip install -e .
    language: python
    always_run: true